# Generated by Django 4.2.2 on 2023-06-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='ren_no',
            new_name='reg_no',
        ),
    ]
