# Generated by Django 4.2.2 on 2023-06-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
