# Generated by Django 4.2.2 on 2023-06-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_children_parent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='hospital_id',
            new_name='hospital',
        ),
    ]
