# Generated by Django 4.2.2 on 2023-06-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_hospital_id_children_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='reg_no',
        ),
    ]
