# Generated by Django 4.2.2 on 2023-06-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_hospital_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
