# Generated by Django 4.2.2 on 2023-06-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
